# Generated by Django 5.0.2 on 2024-02-29 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_cardnumber_card_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userwallet',
            options={'verbose_name': 'User Wallet', 'verbose_name_plural': 'User Wallets'},
        ),
        migrations.AlterModelTable(
            name='userwallet',
            table='user_wallet',
        ),
    ]
