# Generated by Django 5.0.2 on 2024-03-04 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_userwallet_options_alter_userwallet_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='password'),
        ),
    ]
