# Generated by Django 5.0.2 on 2024-03-05 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='password'),
        ),
    ]
