# Generated by Django 5.0.2 on 2024-03-06 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardnumber',
            name='sheba_number',
            field=models.CharField(blank=True, max_length=24, null=True, verbose_name='Sheba Number'),
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/users', verbose_name='image'),
        ),
        migrations.AddField(
            model_name='user',
            name='national_id',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='National ID'),
        ),
    ]
