# Generated by Django 5.0.2 on 2024-03-28 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_cardnumber_sheba_number_user_image_user_national_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardnumber',
            name='card_number',
            field=models.CharField(default=3, max_length=16, unique=True, verbose_name='Card Number'),
            preserve_default=False,
        ),
    ]
