version: '3.9'

services:
  db:
    image: postgres
    restart: unless-stopped
    container_name: foodio-db

    ports:
      - '5432:5432'

    volumes:
      - postgres_data:/var/lib/postgresql/data

    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: foodio_db
      POSTGRES_USER: postgres

    networks:
      foodio-network:
        ipv4_address: 192.168.10.3

  redis:
    image: redis:7.2.4-alpine
    restart: unless-stopped
    container_name: foodio-redis

    ports:
      - '6379:6379'

    networks:
      foodio-network:
        ipv4_address: 192.168.10.4

  rabbit-mq:
    image: rabbitmq:3.13.1-management-alpine
    container_name: foodio-pyamqp
    restart: unless-stopped
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=root

    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

    ports:
      - '5672:5672'
      - '15672:15672'

    networks:
      foodio-network:
        ipv4_address: 192.168.10.5

  rabbitmq_exporter:
    image: kbudde/rabbitmq-exporter
    container_name: rabbitmq_exporter
    environment:
      RABBITMQ_URL: amqp://admin:root@rabbitmq:5672/

    ports:
      - "9419:9419"

    depends_on:
      - rabbit-mq

    networks:
      foodio-network:
        ipv4_address: 192.168.10.10

  mongodb:
    image: mongo:4.4

    container_name: foodio-mongo

    restart: unless-stopped

    env_file:
      - .env

    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: ${MONGO_DB_NAME}
      MONGO_INITDB_USERNAME: ${MONGO_DB_USERNAME}
      MONGO_INITDB_PASSWORD: ${MONGO_DB_PASSWORD}

    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    networks:
      foodio-network:
        ipv4_address: 192.168.10.6

  mongo-express:
    image: mongo-express:0.54
    container_name: mongo-express
    restart: unless-stopped
    ports:
      - '8081:8081'
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_BASICAUTH: false

    links:
      - mongodb:mongodb

    networks:
      foodio-network:
        ipv4_address: 192.168.10.7

    depends_on:
      - mongodb

volumes:
  postgres_data:

  rabbitmq_data:
    driver: local

  mongo-data:

networks:
  foodio-network:
    driver: bridge
    name: foodio-network
    ipam:
      config:
        - subnet: 192.168.10.0/24