version: '3.9'

services:
  db:
    image: postgres
    restart: always
    container_name: foodio-db

    ports:
      - '5432:5432'

    volumes:
      - postgres_data:/var/lib/postgresql/data

    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: foodio_db
      POSTGRES_USER: postgres

    networks:
      - foodio-network

  redis:
    image: redis:7.2.4-alpine
    restart: always
    container_name: foodio-redis

    ports:
      - '6379:6379'

    networks:
      - foodio-network

  rabbit-mq:
    image: rabbitmq:3.13.1-management-alpine
    container_name: foodio-pyamqp
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=password

    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

    ports:
      - '5672:5672'
      - '15672:15672'

    networks:
      - foodio-network

volumes:
  postgres_data:

  rabbitmq_data:
    driver: local

networks:
  foodio-network:
    driver: bridge
    name: foodio-network