version: '3.9'


services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

    restart: always

    container_name: foodio

    volumes:
      - .:/app

    command: /bin/sh -c 'python manage.py migrate && python manage.py runserver 0.0.0.0:8000'

    ports:
      - '8000:8000'

    environment:
      - GITLAB_HOST=gitlab.foodio
      - GITLAB_PORT=80
      - GITLAB_PROTOCOL=http
      - DJANGO_SETTINGS_MODULE=foodio.settings

    depends_on:
      - db
      - redis
      - gitlab

  db:
    image: postgres
    restart: always
    container_name: foodio-db

    ports:
      - '5432:5432'

    volumes:
      - postgres_data:/var/lib/postgresql/data

    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: foodio_db
      POSTGRES_USER: postgres

  redis:
    image: redis:7.2.4-alpine
    restart: always
    container_name: foodio-redis

    ports:
      - '6379:6379'

  rabbit-mq:
    image: rabbitmq:3.13.1-management-alpine
    container_name: foodio-pyamqp
    ports:
      - '5672:5672'

  celery:
    container_name: foodio-celery

    build:
      context: .

    command: celery -A foodio worker -l INFO

    volumes:
      - .:/app

    depends_on:
      - app
      - redis


  gitlab:
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    container_name: 'foodio-gitlab'
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - '/srv/gitlab/config:/etc/gitlab'
      - '/srv/gitlab/data:/var/opt/gitlab'
      - '/srv/gitlab/logs:/var/log/gitlab'
    environment:
      GITLAB_REGISTRY_HOST: registry.gitlab.foodio.com
      GITLAB_REGISTRY_HTTP_SECRET: "0e72e1e4ed14503ef5aec1f9e83d45cc9a1899d13c017bfa4e8685315962e8df"
      GITLAB_REGISTRY_HTTP_KEY: "efd7362ad246a80d6b22017cc715c251a7edf34652a0618dc6f0cbc21dd7290c"
#    registry_nginx:
#      ssl_certificate: /etc/gitlab/ssl/gitlab-registry.crt
#      ssl_certificate_key: /etc/gitlab/ssl/gitlab-registry.key

  registry:
    image: 'gitlab/gitlab-ce:latest'
    container_name: foodio-registry
    ports:
      - '5050:5050'
    volumes:
      - './registry/data:/var/lib/registry'
    depends_on:
      - gitlab

volumes:
  postgres_data: