version: '3.9'


services:
  app:
#    build:
#      context: .
#      dockerfile: Dockerfile

    image: foodio:latest

    restart: always

    container_name: foodio

    volumes:
      - .:/app

    command: /bin/sh -c 'python manage.py migrate && python manage.py runserver 0.0.0.0:8000'

    ports:
      - '8000:8000'

    networks:
      - foodio-network


#    environment:
#      - GITLAB_HOST=gitlab.foodio
#      - GITLAB_PORT=80
#      - GITLAB_PROTOCOL=http
#      - DJANGO_SETTINGS_MODULE=foodio.settings

#    depends_on:
#      - db
#      - redis
#      - gitlab


  celery:
    container_name: foodio-celery

    build:
      context: .

    command: celery -A foodio worker -l INFO -Q seller,product

    volumes:
      - .:/app

    networks:
      - foodio-network

    depends_on:
      - app

#  gitlab:
#    image: 'gitlab/gitlab-ce:latest'
#    restart: always
#    container_name: 'foodio-gitlab'
#    ports:
#      - '80:80'
#      - '443:443'
#    volumes:
#      - '/srv/gitlab/config:/etc/gitlab'
#      - '/srv/gitlab/data:/var/opt/gitlab'
#      - '/srv/gitlab/logs:/var/log/gitlab'
#    environment:
#      GITLAB_REGISTRY_HOST: registry.gitlab.foodio.com
#      GITLAB_REGISTRY_HTTP_SECRET: "0e72e1e4ed14503ef5aec1f9e83d45cc9a1899d13c017bfa4e8685315962e8df"
#      GITLAB_REGISTRY_HTTP_KEY: "efd7362ad246a80d6b22017cc715c251a7edf34652a0618dc6f0cbc21dd7290c"
##    registry_nginx:
##      ssl_certificate: /etc/gitlab/ssl/gitlab-registry.crt
##      ssl_certificate_key: /etc/gitlab/ssl/gitlab-registry.key
#
#  registry:
#    image: 'gitlab/gitlab-ce:latest'
#    container_name: foodio-registry
#    ports:
#      - '5050:5050'
#    volumes:
#      - './registry/data:/var/lib/registry'
#    depends_on:
#      - gitlab


#  prometheus:
#    image: prom/prometheus
#    container_name: prometheus
#    volumes:
#      - ./prometheus.yml:/etc/prometheus/prometheus.yml
#    command:
#      - --config.file=/etc/prometheus/prometheus.yml
#    ports:
#      - "9090:9090"
#    networks:
#      - foodio-network
#    depends_on:
#      - app
#      - celery
#
#  grafana:
#    image: grafana/grafana
#    container_name: grafana
#    volumes:
#      - ./grafana/provisioning:/etc/grafana/provisioning
#    environment:
#      - GF_SECURITY_ADMIN_PASSWORD=password
#    ports:
#      - "3000:3000"
#    networks:
#      - foodio-network
#    depends_on:
#      - prometheus

networks:
  foodio-network:
    external: true
