version: '3.9'


services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: foodio
    volumes:
      - .:/app

    command: /bin/sh -c 'python manage.py migrate && python manage.py runserver 0.0.0.0:8000'

    ports:
      - '8000:8000'

    depends_on:
      - db
      - redis

  db:
    image: postgres
    restart: always
    container_name: foodio-db

    ports:
      - '5432:5432'

    volumes:
      - postgres_data:/var/lib/postgresql/data

    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: foodio_db
      POSTGRES_USER: postgres

  redis:
    image: redis:7.2.4-alpine
    restart: always
    container_name: foodio-redis

    ports:
      - '6379:6379'

  rabbit-mq:
    image: rabbitmq:3.13.1-management-alpine
    container_name: foodio-pyamqp
    ports:
      - '5672:5672'

  celery:
    container_name: foodio-celery

    build:
      context: .

    command: celery -A foodio worker -l INFO

    volumes:
      - .:/app

    depends_on:
      - app
      - redis

#  celery_2:
#    container_name: foodio-celery-2
#    build:
#      context: ./CW_1
#      dockerfile: Dockerfile
#
#    command: celery -A celerytask worker -l INFO
#
#    volumes:
#      - ./CW_1:/celery
#
#    environment:
#      CELERY_BROKER_URL: redis://redis:6379/0
#      CELERY_RESULT_BACKEND: redis://redis:6379/0
#
#    depends_on:
#      - redis

volumes:
  postgres_data: