version: '3.9'


services:
  app:
    build: .
    container_name: foodio
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app

    ports:
      - '8000:8000'

    depends_on:
      - db

  db:
    image: postgres

    container_name: foodio-db

    ports:
      - 5432:5432

    volumes:
      - postgres_data:/var/lib/postgresql/data

    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: foodio_db
      POSTGRES_USER: postgres


volumes:
  postgres_data:


