version: '3.9'

services:
  db:
    image: postgres
    restart: always
    container_name: foodio-db

    ports:
      - '5432:5432'

    volumes:
      - postgres_data:/var/lib/postgresql/data

    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: foodio_db
      POSTGRES_USER: postgres

  redis:
    image: redis:7.2.4-alpine
    restart: always
    container_name: foodio-redis

    ports:
      - '6379:6379'

  rabbit-mq:
    image: rabbitmq:3.13.1-management-alpine
    container_name: foodio-pyamqp
    ports:
      - '5672:5672'


volumes:
  postgres_data:
