# Generated by Django 5.0.2 on 2024-03-15 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameField(
            model_name='midcat',
            old_name='main_cat',
            new_name='parent',
        ),
        migrations.RenameField(
            model_name='subcat',
            old_name='mid_cat',
            new_name='parent',
        ),
    ]
