# Generated by Django 5.0.2 on 2024-03-17 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_productschema_rename_main_cat_midcat_parent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=450, verbose_name='title')),
                ('introduce', models.TextField(blank=True, null=True, verbose_name='introduce')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_categories', to='product.subcat', verbose_name='Sub Category')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
                'db_table': 'Products',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/product', verbose_name='image')),
                ('type', models.CharField(choices=[('banner', 'Banner'), ('sub', 'Sub')], default='sub', max_length=6, verbose_name='type')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='product.product', verbose_name='product')),
            ],
            options={
                'verbose_name': 'image',
                'verbose_name_plural': 'images',
                'db_table': 'product_images',
            },
        ),
        migrations.CreateModel(
            name='ProductProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('property', 'Property'), ('specification', 'Specification')], max_length=14, verbose_name='item type')),
                ('item_name', models.CharField(max_length=50, verbose_name='item name')),
                ('item_detail', models.CharField(max_length=300, verbose_name='item detail')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_properties', to='product.product', verbose_name='product')),
            ],
            options={
                'verbose_name': 'Product property',
                'verbose_name_plural': 'Product properties',
                'db_table': 'Product_properties',
            },
        ),
        migrations.DeleteModel(
            name='ProductSchema',
        ),
    ]
