# Generated by Django 5.0.2 on 2024-04-10 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_maincat_active_remove_midcat_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='celery_task_id',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='celery_task_id'),
        ),
    ]
