# Generated by Django 5.0.2 on 2024-04-10 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_celery_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maincat',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='is active'),
        ),
        migrations.AlterField(
            model_name='midcat',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='is active'),
        ),
        migrations.AlterField(
            model_name='subcat',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='is active'),
        ),
    ]
