# Generated by Django 5.0.2 on 2024-05-16 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_midcat_parent_alter_subcat_parent'),
        ('seller', '0006_seller_celery_task_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
        migrations.AddField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='seller.seller', verbose_name='Seller'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Price')),
                ('is_active', models.BooleanField(default=False, verbose_name='is active')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='product.product', verbose_name='Product')),
            ],
        ),
    ]
