# Generated by Django 5.0.2 on 2024-05-18 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_remove_product_user_product_seller_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='midcat',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='subcat',
            name='parent',
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('is_active', models.BooleanField(default=False, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='product.productcategory')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'db_table': 'categories',
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.productcategory', verbose_name='Category'),
        ),
        migrations.DeleteModel(
            name='MainCat',
        ),
        migrations.DeleteModel(
            name='MidCat',
        ),
        migrations.DeleteModel(
            name='SubCat',
        ),
    ]
