# Generated by Django 5.0.2 on 2024-05-22 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('published', 'Published'), ('pending', 'Pending'), ('draft', 'Draft'), ('not_confirmed', 'Not Confirmed')], default='draft', max_length=13, verbose_name='type'),
        ),
    ]
