# Generated by Django 5.0.2 on 2024-03-24 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='state',
            options={'verbose_name': 'state', 'verbose_name_plural': 'states'},
        ),
        migrations.AlterModelTable(
            name='state',
            table='states',
        ),
    ]
