# Generated by Django 5.0.2 on 2024-03-24 12:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_alter_state_options_alter_state_table'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_class', models.CharField(max_length=250, verbose_name='Work Class')),
                ('work_class_number', models.CharField(max_length=30, verbose_name='Work Class Number')),
                ('address', models.CharField(help_text='Enter your work address', max_length=300, verbose_name='Address')),
                ('is_active', models.BooleanField(default=False, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sellers', to='seller.state', verbose_name='states')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seller', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Seller',
                'verbose_name_plural': 'Sellers',
                'db_table': 'Sellers',
            },
        ),
    ]
