# Generated by Django 5.0.2 on 2024-03-24 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0003_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='seller.state', verbose_name='parent'),
        ),
        migrations.AddField(
            model_name='state',
            name='type',
            field=models.CharField(choices=[('state', 'State'), ('city', 'City')], default=None, max_length=5, verbose_name='type'),
        ),
    ]
