# Generated by Django 5.0.2 on 2024-04-05 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0005_seller_not_confirmed_cause'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='celery_task_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='celery_task_id'),
        ),
    ]
