# Generated by Django 5.0.2 on 2024-03-04 19:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_id', models.CharField(max_length=11)),
                ('sheba_number', models.CharField(max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/admins/%Y/%m/%d/', verbose_name='image')),
                ('position', models.CharField(choices=[('financial', 'Financial'), ('technical', 'Technical'), ('support', 'Support'), ('product', 'Product')], default='financial', max_length=10, verbose_name='Position')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Admin',
                'verbose_name_plural': 'Admins',
                'db_table': 'admin_section',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_id', models.CharField(max_length=11)),
                ('sheba_number', models.CharField(max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/admins/%Y/%m/%d/', verbose_name='image')),
                ('position', models.CharField(choices=[('financial', 'Financial'), ('technical', 'Technical'), ('support', 'Support'), ('product', 'Product')], default='financial', max_length=10, verbose_name='Position')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staffs', to='admin_section.admin', verbose_name='admin_section')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'staff',
                'verbose_name_plural': 'staffs',
                'db_table': 'staffs',
            },
        ),
    ]
