# Generated by Django 5.0.2 on 2024-03-04 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_section', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='national_id',
            field=models.CharField(max_length=10, verbose_name='National ID'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='sheba_number',
            field=models.CharField(max_length=24, verbose_name='Sheba Number'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='national_id',
            field=models.CharField(max_length=10, verbose_name='National ID'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='sheba_number',
            field=models.CharField(max_length=24, verbose_name='Sheba Number'),
        ),
    ]
