# Generated by Django 5.0.2 on 2024-03-04 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_section', '0003_alter_staff_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_staff', to='admin_section.admin', verbose_name='admin_section'),
        ),
    ]
