# Generated by Django 5.0.2 on 2024-03-06 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_section', '0005_alter_admin_user_alter_staff_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='image',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='national_id',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='sheba_number',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='image',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='national_id',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='sheba_number',
        ),
        migrations.AlterField(
            model_name='staff',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_staff', to='admin_section.admin', verbose_name='Admin User'),
        ),
    ]
