# Generated by Django 5.0.2 on 2024-03-24 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_section', '0006_remove_admin_image_remove_admin_national_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='position',
            field=models.CharField(choices=[('financial', 'Financial'), ('technical', 'Technical'), ('support', 'Support'), ('product', 'Product')], default=None, max_length=10, verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='position',
            field=models.CharField(choices=[('financial', 'Financial'), ('technical', 'Technical'), ('support', 'Support'), ('product', 'Product')], default=None, max_length=10, verbose_name='Position'),
        ),
    ]
